apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: CloudOps-Cluster
  region: ap-south-1

nodeGroups:
  - name: ng-1 
    instanceType: t3.large
    desiredCapacity: 1
    ssh:
      allow: false
    